export const SET_USER = 'SET_USER';
export const ERRORS = 'ERRORS';
export const SET_PROFILE = 'SET_PROFILE';
export const SET_PROFILES = 'SET_PROFILES';
export const DELETE_PROFILE = 'DELETE_PROFILE';
export const UPDATE_PROFILE = 'UPDATE_PROFILE';
export const BAN_PROFILE = 'BAN_PROFILE';

//! Products
export const GET_PRODUCTS = 'GET_PRODUCTS';
export const PRODUCT_LIST_REQUEST = 'PRODUCT_LIST_REQUEST';
export const PRODUCT_LIST_SUCCESS = 'PRODUCT_LIST_SUCCESS';
export const PRODUCT_LIST_FAIL = 'PRODUCT_LIST_FAIL';

//! Basket
export const ADD_TO_BASKET_REQUEST = 'ADD_TO_BASKET_REQUEST';
export const ADD_TO_BASKET_SUCCESS = 'ADD_TO_BASKET_SUCCESS';
export const ADD_TO_BASKET_FAILURE = 'ADD_TO_BASKET_FAILURE';
export const GET_BASKET_REQUEST = 'GET_BASKET_REQUEST';
export const GET_BASKET_SUCCESS = 'GET_BASKET_SUCCESS';
export const GET_BASKET_FAILURE = 'GET_BASKET_FAILURE';

export const PUT_BASKET_REQUEST = 'PUT_BASKET_REQUEST';
export const PUT_BASKET_SUCCESS = 'PUT_BASKET_SUCCESS';
export const PUT_BASKET_FAILURE = 'PUT_BASKET_FAILURE';